// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYsx8_J_DITWvutx2Oz1GDpSfKOm0-3ig',
    appId: '1:458423044554:web:2a6ebee8f2692193f8a733',
    messagingSenderId: '458423044554',
    projectId: 'quizflutter-663a9',
    authDomain: 'quizflutter-663a9.firebaseapp.com',
    storageBucket: 'quizflutter-663a9.firebasestorage.app',
    measurementId: 'G-CG8ZCTKEHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp_RoawmI6rq1DxhSqBzx9u6r6az1zYlo',
    appId: '1:458423044554:android:dd0b02e7372b8966f8a733',
    messagingSenderId: '458423044554',
    projectId: 'quizflutter-663a9',
    storageBucket: 'quizflutter-663a9.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYsx8_J_DITWvutx2Oz1GDpSfKOm0-3ig',
    appId: '1:458423044554:web:83ef6b8513e14ae7f8a733',
    messagingSenderId: '458423044554',
    projectId: 'quizflutter-663a9',
    authDomain: 'quizflutter-663a9.firebaseapp.com',
    storageBucket: 'quizflutter-663a9.firebasestorage.app',
    measurementId: 'G-KETC53WQZ7',
  );
}
